### ISSUE TITLE
README.md - typo

### ISSUE THREAD

**Issue by tiln7** [SidSidSid16/COVID19-Tracker#2]
Hi,

you have a typo here:

<img width="673" alt="Screenshot at Aug 08 23-05-00" src="https://user-images.githubusercontent.com/39374789/89719734-c54d7e00-d9cb-11ea-8219-a0b7032a7ffd.png">

**Comment by SidSidSid16** [comment]
Doesn't seem to be a typo. Please refer to the Python documentation, [here](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/). If I'm missing something and it actually is a typo, please let me know, otherwise, I shall be closing this issue.

Thanks!

**Comment by tiln7** [comment]
Just realized you named your virtual environment “env”.

Everything ok, sorry for the confusion.

Rgrds

**Comment by SidSidSid16** [comment]
No worries, I'll close this issue.

Thank you!
